# Generated by Django 4.1.4 on 2023-09-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_class', models.CharField(max_length=10, verbose_name='Hazard Class')),
                ('reason_regulation', models.TextField(blank=True, null=True, verbose_name='\u200bReason for Regulation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('label', models.ImageField(blank=True, null=True, upload_to='apps/aviastates/dgr/dangerous_goods_labels/', verbose_name='Label Image')),
            ],
        ),
        migrations.CreateModel(
            name='DangerousGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UN_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='UN Number')),
                ('proper_shipping_name', models.CharField(max_length=255, verbose_name='Proper Shipping Name')),
                ('hazard_class', models.CharField(max_length=10, verbose_name='Hazard Class')),
                ('packing_group', models.CharField(blank=True, max_length=5, null=True, verbose_name='Packing Group')),
                ('subsidiary_risk', models.CharField(blank=True, max_length=10, null=True, verbose_name='Subsidiary Risk')),
                ('packing_instructions', models.TextField(blank=True, null=True, verbose_name='Packing Instructions')),
                ('special_provisions', models.TextField(blank=True, null=True, verbose_name='Special Provisions')),
                ('packaging_instructions', models.TextField(blank=True, null=True, verbose_name='Packaging Instructions')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
            ],
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_number', models.CharField(max_length=5, verbose_name='Sub-Division Number')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('label', models.ImageField(blank=True, null=True, upload_to='apps/aviastates/dgr/dangerous_goods_labels/', verbose_name='Label Image')),
                ('base_dg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='dgr.basedg')),
            ],
        ),
    ]
