# Generated by Django 4.1.4 on 2023-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedg',
            name='hazard_class',
            field=models.CharField(max_length=50, verbose_name='Hazard Class'),
        ),
    ]
