# Generated by Django 4.1.4 on 2023-09-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='registration_number',
            new_name='registrationNumber',
        ),
    ]
