# Generated by Django 4.1.4 on 2023-09-11 05:49

import apps.flights.models.document_model
import apps.flights.models.file_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CharterFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_date', models.DateField(blank=True, null=True)),
                ('flight_time', models.TimeField(blank=True, null=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_route', models.CharField(blank=True, max_length=100, null=True)),
                ('iata', models.CharField(blank=True, max_length=3)),
                ('icao', models.CharField(blank=True, max_length=4)),
                ('action_code', models.CharField(blank=True, max_length=15)),
                ('message_code', models.TextField(blank=True, default='', null=True)),
                ('slot_msg', models.CharField(blank=True, max_length=100, null=True)),
                ('state_status', models.CharField(choices=[('New', 'New'), ('StandBy', 'StandBy'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled')], default='New', max_length=20)),
                ('hand_status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('OnObserve', 'OnObserve'), ('OnRamp', 'OnRamp'), ('GroundCompleted', 'GroundCompleted')], default='New', max_length=20)),
                ('trip_status', models.CharField(choices=[('Opened', 'Opened'), ('Angaged', 'Angaged'), ('Closed', 'Closed')], default='Opened', max_length=20)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airlines.aircraft')),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airlines.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=apps.flights.models.document_model.document_upload_to)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.charterflight')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=apps.flights.models.file_model.file_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='FlightProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, to='flights.document')),
                ('files', models.ManyToManyField(blank=True, to='flights.file')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_project', to='flights.charterflight')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('iata', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('uld_number', models.CharField(blank=True, max_length=20, null=True)),
                ('awb', models.CharField(blank=True, max_length=20, null=True)),
                ('route_from', models.CharField(blank=True, max_length=10, null=True)),
                ('route_to', models.CharField(blank=True, max_length=10, null=True)),
                ('pieces_type', models.CharField(blank=True, max_length=3, null=True)),
                ('kilos', models.IntegerField(blank=True, null=True)),
                ('cubic_meter', models.IntegerField(blank=True, null=True)),
                ('last_pics', models.IntegerField(blank=True, null=True)),
                ('goods', models.CharField(blank=True, max_length=100, null=True)),
                ('special_handling_code', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TripFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_created=True)),
                ('trip_number', models.CharField(editable=False, max_length=20)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('LDM', 'Load Distribution Message'), ('CPM', 'Customs Pre-arrival Message'), ('FFM', 'Freight Forwarder Message'), ('FWB', 'Freight Waybill'), ('FFA', 'Freight Arrival Message'), ('MVT', 'Movement Message')], max_length=3)),
                ('tracking_date', models.DateField(default=django.utils.timezone.now)),
                ('tracking_time', models.TimeField(default=django.utils.timezone.now)),
                ('message_content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trip_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.tripfile')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.charterflight')),
                ('flight_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightproject')),
            ],
        ),
        migrations.CreateModel(
            name='Msgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_date', models.DateField(default=django.utils.timezone.now)),
                ('tracking_time', models.TimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trip_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.tripfile')),
            ],
        ),
        migrations.AddField(
            model_name='flightproject',
            name='notes',
            field=models.ManyToManyField(blank=True, to='flights.note'),
        ),
        migrations.AddField(
            model_name='file',
            name='flight_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightproject'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_time', models.TimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('DMG_A', 'Damage of Aircraft'), ('DMG_SHP', 'Damage of shipment'), ('DMG_QIP', 'Damage of equipment'), ('STF_EVN', 'Stuff events'), ('NTCLS', 'Not classified')], default='', max_length=10)),
                ('description', models.TextField()),
                ('attachment', models.ManyToManyField(to='flights.attachment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trip_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.tripfile')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='flight_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightproject'),
        ),
        migrations.AddField(
            model_name='charterflight',
            name='tripfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.tripfile'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.file'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='trip_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.tripfile'),
        ),
    ]
