# Generated by Django 4.1.4 on 2023-08-25 16:06

import apps.flights.models.document_model
import apps.flights.models.file_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=apps.flights.models.document_model.document_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=apps.flights.models.file_model.file_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure')], max_length=10)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_route', models.CharField(default='XXX', max_length=3)),
                ('ac_reg_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('handling_status', models.CharField(choices=[('New', 'New'), ('StandBy', 'StandBy'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled')], default='New', max_length=20)),
                ('create_flight_project', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlightProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fprj_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('flight_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightproject')),
            ],
        ),
        migrations.CreateModel(
            name='LDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldm_telexes', to='flights.flight')),
            ],
        ),
    ]
