# Generated by Django 4.1.4 on 2023-09-17 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airlines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telex',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telex',
            name='trip_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.tripfile'),
        ),
        migrations.AddField(
            model_name='shipmentflight',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.charterflight'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='uld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.uld'),
        ),
        migrations.AddField(
            model_name='note',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.charterflight'),
        ),
        migrations.AddField(
            model_name='note',
            name='flight_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightproject'),
        ),
        migrations.AddField(
            model_name='msgs',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='msgs',
            name='trip_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.tripfile'),
        ),
        migrations.AddField(
            model_name='flightproject',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightproject',
            name='documents',
            field=models.ManyToManyField(blank=True, to='flights.document'),
        ),
        migrations.AddField(
            model_name='flightproject',
            name='files',
            field=models.ManyToManyField(blank=True, to='flights.file'),
        ),
        migrations.AddField(
            model_name='flightproject',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_project', to='flights.charterflight'),
        ),
        migrations.AddField(
            model_name='flightproject',
            name='notes',
            field=models.ManyToManyField(blank=True, to='flights.note'),
        ),
        migrations.AddField(
            model_name='file',
            name='flight_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightproject'),
        ),
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.ManyToManyField(to='flights.attachment'),
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='trip_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.tripfile'),
        ),
        migrations.AddField(
            model_name='document',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.charterflight'),
        ),
        migrations.AddField(
            model_name='document',
            name='flight_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightproject'),
        ),
        migrations.AddField(
            model_name='charterflight',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airlines.aircraft'),
        ),
        migrations.AddField(
            model_name='charterflight',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airlines.airline'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.file'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='trip_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.tripfile'),
        ),
    ]
