# Generated by Django 4.1.4 on 2023-09-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uld_number', models.CharField(max_length=20)),
                ('awb', models.CharField(max_length=20)),
                ('route_from', models.CharField(max_length=3)),
                ('route_to', models.CharField(max_length=3)),
                ('pieces_type', models.CharField(max_length=2)),
                ('kilos', models.PositiveIntegerField()),
                ('cubic_meter', models.PositiveIntegerField()),
                ('last_pics', models.CharField(max_length=3)),
                ('goods', models.CharField(max_length=100)),
                ('special_handling', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
