# Generated by Django 4.1.4 on 2023-08-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_flight_date_remove_flight_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure')], default='', max_length=10),
        ),
    ]
