# Generated by Django 4.1.4 on 2023-09-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='special_handling',
            new_name='flight_number',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='message',
        ),
        migrations.AddField(
            model_name='shipment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='iata',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='registration_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='special_handling_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='awb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cubic_meter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='goods',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='kilos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='last_pics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pieces_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='route_from',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='route_to',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='uld_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
