# Generated by Django 4.1.4 on 2023-08-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_ac_reg_number_alter_flight_aircraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ldm_telex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flighs', to='flights.ldm'),
        ),
    ]
