# Generated by Django 4.1.4 on 2023-09-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_special_handling_shipment_flight_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
