# Generated by Django 4.1.4 on 2023-08-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_flight_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_route',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
