# Generated by Django 4.1.4 on 2023-09-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_shipment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='message',
            field=models.TextField(),
        ),
    ]
