# Generated by Django 4.1.4 on 2023-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_charterflight'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterflight',
            name='message_code',
            field=models.TextField(default=''),
        ),
    ]
