# Generated by Django 4.1.4 on 2023-08-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_charterflight_message_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charterflight',
            name='segment_date_time',
        ),
        migrations.RemoveField(
            model_name='charterflight',
            name='segment_description',
        ),
        migrations.RemoveField(
            model_name='charterflight',
            name='segment_route',
        ),
        migrations.AddField(
            model_name='charterflight',
            name='action_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
