# Generated by Django 4.1.4 on 2023-09-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_remove_flightproject_fprj_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripfile',
            name='unique_id',
        ),
    ]
