# Generated by Django 4.1.4 on 2023-09-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_shipment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
