# Generated by Django 4.1.4 on 2023-08-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_remove_charterflight_segment_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterflight',
            name='slot_msg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
