# Generated by Django 4.1.4 on 2023-08-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_charterflight_slot_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charterflight',
            name='slot_msg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
