# Generated by Django 4.1.4 on 2023-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_alter_charterflight_slot_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterflight',
            name='flight_data_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
