# Generated by Django 4.1.4 on 2023-08-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_charterflight_flight_data_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charterflight',
            old_name='flight_data',
            new_name='flight_date',
        ),
    ]
